//This file was automatically generated by LevelHelper 2
//based on the class template defined by the user.
//For more info please visit: http://www.gamedevhelper.com

#import "LHUtils.h"
#import "LHScene.h"
#import "LHUserProperties.h"

@implementation ButtonInfo
{
	__weak id<LHNodeProtocol> node;
	NSString* levelFile;
	float levelID;
}

@synthesize levelFile;
@synthesize levelID;


-(void) dealloc{
	LH_SAFE_RELEASE(levelFile);

	LH_SUPER_DEALLOC();
}

+(id) customClassInstanceWithNode:(id<LHNodeProtocol>)n{
	return [[self alloc] initWithNode:n];
}

-(id) initWithNode:(id<LHNodeProtocol>)n{
	if(self = [super init]){
		node = n;
	}
	return self;
}

-(id<LHNodeProtocol>) node{
	return node;
}
-(NSString*) className{
	return NSStringFromClass([self class]);
}
-(void) setPropertiesFromDictionary:(NSDictionary*)dictionary
{

	if([dictionary objectForKey:@"levelFile"])
		[self setLevelFile:[dictionary objectForKey:@"levelFile"]];

	if([dictionary objectForKey:@"levelID"])
		[self setLevelID:[[dictionary objectForKey:@"levelID"] floatValue]];

}

@end


@implementation LevelInfo
{
	__weak id<LHNodeProtocol> node;
	float levelID;
}

@synthesize levelID;


-(void) dealloc{

	LH_SUPER_DEALLOC();
}

+(id) customClassInstanceWithNode:(id<LHNodeProtocol>)n{
	return [[self alloc] initWithNode:n];
}

-(id) initWithNode:(id<LHNodeProtocol>)n{
	if(self = [super init]){
		node = n;
	}
	return self;
}

-(id<LHNodeProtocol>) node{
	return node;
}
-(NSString*) className{
	return NSStringFromClass([self class]);
}
-(void) setPropertiesFromDictionary:(NSDictionary*)dictionary
{

	if([dictionary objectForKey:@"levelID"])
		[self setLevelID:[[dictionary objectForKey:@"levelID"] floatValue]];

}

@end

