//This file was automatically generated by LevelHelper 2
//based on the class template defined by the user.
//For more info please visit: http://www.gamedevhelper.com

#import "LHNodeProtocol.h"
#import "LHUserPropertyProtocol.h"


#ifndef __LH_USER_PROPERTY_BUTTONINFO__
#define __LH_USER_PROPERTY_BUTTONINFO__
@interface ButtonInfo : NSObject<LHUserPropertyProtocol>

@property (nonatomic, retain) NSString* levelFile;
@property float levelID;

+(id) customClassInstanceWithNode:(id<LHNodeProtocol>)node;

-(id) initWithNode:(id<LHNodeProtocol>)node;

-(NSString*) className;

-(id<LHNodeProtocol>) node;

-(void) setPropertiesFromDictionary:(NSDictionary*)dictionary;

@end
#endif //__LH_USER_PROPERTY_BUTTONINFO__


#ifndef __LH_USER_PROPERTY_LEVELINFO__
#define __LH_USER_PROPERTY_LEVELINFO__
@interface LevelInfo : NSObject<LHUserPropertyProtocol>

@property float levelID;

+(id) customClassInstanceWithNode:(id<LHNodeProtocol>)node;

-(id) initWithNode:(id<LHNodeProtocol>)node;

-(NSString*) className;

-(id<LHNodeProtocol>) node;

-(void) setPropertiesFromDictionary:(NSDictionary*)dictionary;

@end
#endif //__LH_USER_PROPERTY_LEVELINFO__

